name: Java CI with Maven

on:
  push:
    branches: main
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
          fetch-depth: 0 
          
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: 'maven'
        
    - name: Build with Maven
      run: mvn clean verify --file vibe-flow/pom.xml
      
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: packaged-jar
        path: vibe-flow/target/*.jar
        
  frontend-tests-and-bundle:
    runs-on: ubuntu-latest
    
    needs: build
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: cd vibe-flow-frontend && npm install
      
    - name: Run frontend tests
      run: cd vibe-flow-frontend && npm test
      
    - name: Build frontend bundle
      if: success()
      run: cd vibe-flow-frontend && npx webpack
